<?php

namespace AppBundle\Repository;

/**
 * RegistrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistrationRepository extends \Doctrine\ORM\EntityRepository
{
//    public function getBeschikbareLessen($user)
//    {
//        $em=$this->getEntityManager();
//        $query=$em->createQuery('SELECT l FROM AppBundle:Lesson l WHERE :r NOT MEMBER OF r.user where r.lesson');
//
//        $query->setParameter('user',$user);
//
//        return $query->getResult();
//    }
}

//lesson where user not member of registration where