<?php

namespace AppBundle\Repository;


use Doctrine\ORM\EntityRepository;
/**
 * TrainingRepository
 *
 * This class was generated by the Doctrine ORM. Ad d your own custom
 * repository methods below.
 */
class TrainingRepository extends EntityRepository
{

}
